bolero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import logout_then_login
from django.views.generic.base import RedirectView
from players.views import LoginView

urlpatterns = [
    path('', RedirectView.as_view(url='/groups')),
    path('admin/', admin.site.urls),
    path('groups/', include('groups.urls')),
    path('games/', include('games.urls')),
    path('players/', include('players.urls')),
    path('login', LoginView.as_view(), name='login'),
    path('logout', logout_then_login, name='logout')
]

games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<code>/game-create/', views.create, name='game-create'),
    path('<code>/game-remove/<game_id>', views.remove, name='game-remove'),
    path('<code>/game-edit/<game_id>', views.edit, name='game-edit'),
    path('<code>/game-subscribe/<game_id>', views.subscribe, name='game-subscribe'),
    path('<code>/game-unsubscribe/<game_id>', views.unsubscribe, name='game-unsubscribe'),
]

games/models.py
from django.db import models

from groups.models import Group
from players.models import Player


class Game(models.Model):
    name = models.CharField(verbose_name='nome', max_length=63)
    date_time = models.DateTimeField(verbose_name='data e hora')
    players = models.ManyToManyField(Player, related_name='games', verbose_name='jogadores')
    group = models.ForeignKey(Group, verbose_name='grupo', on_delete=models.CASCADE)
    local = models.CharField(verbose_name='local da partida', max_length=255)
    max_players = models.IntegerField(verbose_name='quantidade máxima de jogadores')

    def __str__(self):
        return str(self.name)
    
    class Meta:
        verbose_name = 'jogo'
        verbose_name_plural = 'jogos'

games/forms.py
from django import forms
from django.db.models.base import Model
from django.forms import ModelForm, fields
from .models import Game


class GameCreateForm(ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'date_time', 'local', 'max_players']

games/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls.base import reverse
from games.models import Game
from games.services import can_player_subscribe, create_game, delete_game, get_game, subscribe_player, unsubscribe_player

from groups.models import Group
from groups.services import player_has_permission
from players.services import get_player
from .forms import GameCreateForm
from django.shortcuts import get_object_or_404
from django.contrib import messages


@login_required
def create(request, code):
    group = get_object_or_404(Group, code=code)
    if request.method == 'POST':
        form = GameCreateForm(request.POST)
        if form.is_valid():
            game = create_game(form.cleaned_data, request.user, group)
            messages.success(request, f'Jogo {game} criado com sucesso!')
            return redirect(reverse('group-detail', args=[group.code]))
        else:
            messages.error(request, f'Dados inválidos: {form.errors}')
    else:
        form = GameCreateForm()
    return render(request, "games/create.html", {
        'form': form
    })

@login_required
def edit(request, code, game_id):
    group = get_object_or_404(Group, code=code)
    game = get_game(group, game_id)
    if not group:
        messages.error(request, 'Jogo não encontrado.')
        return redirect(reverse('groups'))
    elif group.admin.user != request.user:
        messages.error(request, 'Usuário não tem permissão.')
        return redirect(reverse('groups'))

    if request.method == 'POST':
        form = GameCreateForm(data=request.POST, instance=game)
        if form.is_valid():
            form.save()
            messages.success(request, f'Jogo {game} atualizado.')
            return redirect(reverse('group-detail', args=[group.code]))
        else:
            messages.error(request, f'Dados inválidos: {form.errors}')
    else:
        form = GameCreateForm(instance=game)
    return render(request, "games/edit.html", {
        'form': form, 'game': game
    })

@login_required
def remove(request, code, game_id):
    group = get_object_or_404(Group, code=code)
    game = get_game(group, game_id)
    if not game:
        messages.error(request, 'Jogo não encontrado.')
        return redirect(reverse('group-detail', args=[code]))
    elif group.admin.user != request.user:
        messages.error(request, 'Usuário não tem permissão.')
        return redirect(reverse('group-detail', args=[code]))

    delete_game(game)
    messages.success(request, f'Jogo {game} removido com sucesso!')
    return redirect(reverse('group-detail', args=[code]))

@login_required
def subscribe(request, code, game_id):
    group = get_object_or_404(Group, code=code)
    game = get_object_or_404(Game, group=group, id=game_id)
    player = get_player(request.user)
    
    if player_has_permission(group, player):
        if can_player_subscribe(game):
            subscribe_player(game, player)
            messages.success(request, f'Jogagor {player} se inscreveu no jogo {game}')
        else:
            messages.error(request, f'O jogo já está cheio!')
    else:
        messages.warning(request, f'É necessário fazer parte do grupo para entrar neste jogo!')
            
    return redirect(reverse('group-detail', args=[code]))

@login_required
def unsubscribe(request, code, game_id):
    group = get_object_or_404(Group, code=code)
    game = get_object_or_404(Game, group=group, id=game_id)
    player = get_player(request.user)
    
    if player_has_permission(group, player):
        unsubscribe_player(game, player)
        messages.warning(request, f'Jogagor {player} saiu do jogo {game}')
    else:
        messages.error(request, f'É necessário fazer parte do grupo para sair deste jogo?!')
            
    return redirect(reverse('group-detail', args=[code]))

games/templates/games/create.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
<h3>Criar partida</h3>
<form method="post" class="form">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" for="id_name">Nome</label>
        <input type="text" name="name" maxlength="63" class="form-control" title="" required="" id="id_name">
    </div>
    <div class="mb-3">
        <label class="form-label" for="id_date_time">Date time</label>
        <input type="datetime-local" name="date_time" class="form-control" title="" required="" id="id_date_time">
    </div>
    <div class="mb-3">
        <label class="form-label" for="id_local">Local da partida</label>
        <input type="text" name="local" maxlength="255" class="form-control" title="" required="" id="id_local">
    </div>
    <div class="mb-3">
        <label class="form-label" for="id_max_players">Quantidade máxima de jogadores</label>
        <input type="number" name="max_players" class="form-control" title="" required="" id="id_max_players">
    </div>
    {% buttons %}
    <button class="btn btn-primary" type="submit">Salvar</button>
    {% endbuttons %}
</form>
{% endblock %}

games/templates/games/edit.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
<h3>Editar jogo</h3>
<form method="post" class="form">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" for="id_name">Nome</label>
        <input type="text" name="name" maxlength="63" class="form-control" title="" required="" id="id_name" value="{{ form.name.value }}">
    </div>
    <div class="mb-3">
        <label class="form-label" for="id_date_time">Date time</label>
        <input type="datetime-local" name="date_time" class="form-control" title="" required="" id="id_date_time" value="{{ form.date_time.value|date:'c' }}">
    </div>
    <div class="mb-3">
        <label class="form-label" for="id_local">Local da partida</label>
        <input type="text" name="local" maxlength="255" class="form-control" title="" required="" id="id_local" value="{{ form.local.value }}">
    </div>
    <div class="mb-3">
        <label class="form-label" for="id_max_players">Quantidade máxima de jogadores</label>
        <input type="number" name="max_players" class="form-control" title="" required="" id="id_max_players" value="{{ form.max_players.value }}">
    </div>
    {% buttons %}
    <button class="btn btn-primary" type="submit">Salvar</button>
    {% endbuttons %}
</form>
{% endblock %}

games/templates/games/list.html
{% if player_in_group and games %}
<h4>Jogos</h4>
<div class='row'>
    {% for game in games %}
    <div class='col col-md-6 col-lg-4'>
        <div class="bg-gradient bg-game rounded-3 p-3">
            <small>{{ game.date_time }}</small>
            <h3>{{ game.name }}</h3>
            <hr>
            <p><strong>Local: </strong>{{ game.local }}</p>
            <p><strong>Jogadores/máximo: </strong>{{ game.players.count }}/{{ game.max_players }}</p>
            {% for player in game.players.all %}
                {% if user_player == player %}
                <span class="badge bg-primary"><i class="bi bi-person-fill"></i> {{ player.user }}</span>
                {% else %}
                <span class="badge bg-secondary"><i class="bi bi-person-fill"></i> {{ player.user }}</span>
                {% endif %}
            {% endfor %}
            
            <div class='float-end game-buttons'>
                <a href='{% url "game-edit" group.code game.id%}' class='btn btn-secondary' title='editar jogo'>
                    <i class="bi bi-pencil-fill"></i>
                </a>
                <a href='{% url "game-remove" group.code game.id %}' class='btn btn-danger' title='deletar jogo'>
                    <i class="bi bi-trash-fill"></i>
                </a>
                {% if user_player in game.players.all %}
                <a href='{% url "game-unsubscribe" group.code game.id %}'class='btn btn-secondary' title='sair do jogo'>
                    Sair <i class="bi bi-box-arrow-down-left"></i>
                </a>
                {% else %}
                <a href='{% url "game-subscribe" group.code game.id %}'class='btn btn-primary' title='entrar no jogo'>
                    Entrar <i class="bi bi-box-arrow-in-up-right"></i>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}